package com.example.model;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "products") // Specifies MongoDB collection
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Product {
    @Id
    private String id; // Automatically generated by MongoDB

    private String name;
    private String description;
    private double price;
    private int quantity;
    private String category;
}